Repository jenkinsci/data-tables-api-plugin, pull requests merged in 2023-06, with the labels that each got.

#356 Enable built-in auto-save functionality of DataTables
  README.adoc
  src/main/webapp/js/table.js
Labels: internal

#359 Bump version of NPM to npm-v18.12.0
  package.json
  pom.xml
Labels: dependencies

#360 Do not save state of tables when Prototype is still installed
  src/main/webapp/js/table.js
Labels: enhancement

#364 Add ability to disable paging
  src/main/java/io/jenkins/plugins/datatables/TableConfiguration.java
  src/main/webapp/js/table.js
  src/test/java/io/jenkins/plugins/datatables/TableConfigurationTest.java
Labels: enhancement
